# requiring the environment of NodeJS 10
image: jiuxiaxixi/gitbook

# add 'node_modules' to cache for speeding up builds
cache:
  paths:
    - node_modules/ # Node modules and dependencies

before_script:
  - gitbook install # add any requested plugins in book.json
  - book sm -i node_modules,_book

    
# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - gitbook build . public # build to public path
  artifacts:
    paths:
      - public

  only:
    - master # this job will affect only the 'master' branch

